// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace E_Cart_WebApp.Models
{
    [Table("ProductOrderDetail")]
    public partial class ProductOrderDetail
    {
        [Key]
        public int OrderID { get; set; }
        public int? ProductID { get; set; }
        public short? Quantity { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? UnitPrice { get; set; }
        public int? Discount { get; set; }
    }
}