// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace E_Cart_WebApp.Models
{
    [Table("UserMaster")]
    public partial class UserMaster
    {
        public UserMaster()
        {
            ProductsCarts = new HashSet<ProductsCart>();
        }

        [Key]
        public int UserId { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Name { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string UserName { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Password { get; set; }
        public bool? IsActive { get; set; }
        public int? Role { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }

        [ForeignKey("Role")]
        [InverseProperty("UserMasters")]
        public virtual RoleMaster RoleNavigation { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<ProductsCart> ProductsCarts { get; set; }
    }
}