// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace E_Cart_WebAPI.Models
{
    [Table("RoleMaster")]
    public partial class RoleMaster
    {
        public RoleMaster()
        {
            UserMasters = new HashSet<UserMaster>();
        }

        [Key]
        public int RoleId { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string RoleDescription { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }

        [InverseProperty("RoleNavigation")]
        public virtual ICollection<UserMaster> UserMasters { get; set; }
    }
}