// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using E_Cart_WebApp.Models;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace E_Cart_WebApp.Data
{
    public partial class NorthwindContext : IdentityDbContext
    {
        public NorthwindContext()
        {
        }

        public NorthwindContext(DbContextOptions<NorthwindContext> options)
            : base(options)
        {
        }

        
    }
}