// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using E_Cart_WebAPI.Models;

namespace E_Cart_WebAPI.Data
{
    public partial class NorthwindContext
    {

        [DbFunction("GetOrdersInGivenYear", "dbo")]
        public IQueryable<GetOrdersInGivenYearResult> GetOrdersInGivenYear(string Year)
        {
            return FromExpression(() => GetOrdersInGivenYear(Year));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetOrdersInGivenYearResult>().HasNoKey();
        }
    }
}
